# config.yml
ores:
  COAL_ORE:
    minY: 1
    maxY: 130
    chance: 0.00142

  IRON_ORE:
    minY: 1
    maxY: 130
    chance: 0.00088

  GOLD_ORE:
    minY: 1
    maxY: 60
    chance: 0.00036

  REDSTONE_ORE:
    minY: 1
    maxY: 60
    chance: 0.00102

  LAPIS_ORE:
    minY: 1
    maxY: 60
    chance: 0.00059

  DIAMOND_ORE:
    minY: 1
    maxY: 21
    chance: 0.00033

  EMERALD_ORE:
    minY: 1
    maxY: 21
    chance: 0.00022
